name: PaperDeathMessages
version: 2.1.3
main: com.floogoobooq.blackomega.paperdeathmessages.PaperDeathMessages
api-version: 1.18
commands:
  logdeaths:
    description: Logs player's deaths
    usage: Usage is /logdeaths <start | stop> <player>